"""Add Job indexes for scale

Revision ID: 012
Revises: 011
Create Date: 2026-02-21 12:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012'
down_revision: Union[str, None] = '011_manual_overrides'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_batch_id'), 'jobs', ['batch_id'], unique=False)
    op.create_index('ix_jobs_status_created_at', 'jobs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_status_created_at', table_name='jobs')
    op.drop_index(op.f('ix_jobs_batch_id'), table_name='jobs')
    # ### end Alembic commands ###
